application: rasmuserik-test
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /timelog.*
  script: timelog/timelog.py
- url: /bettinatimelog.*
  script: timelog-bettina/timelog.py
- url: /.*
  script: storage.py
